import { useState } from "react";
import { ArrowRight, Film, Play, Sparkles } from "lucide-react";

const clips = [
  ["A · 00:03–00:07", "明显油污，适合作为问题开场。", "价值 94 · 推荐"],
  ["B · 00:06–00:11", "产品正面与容量可识别。", "价值 91 · 产品锚点"],
  ["B · 00:12–00:21", "喷洒动作完整，手部无遮挡。", "价值 89 · 使用过程"],
  ["A · 00:24–00:33", "擦拭过程连续，节奏可压缩。", "价值 84 · 可用"],
  ["B · 00:28–00:38", "清洁结果清楚，可与开场配对。", "价值 96 · 前后对比"]
];

export function MaterialIntelligenceWorkbench({ demo = false, onRevise }: { demo?: boolean; onRevise?: (instruction: string) => void }) {
  const [revision, setRevision] = useState("");
  return <section className="page-section intelligence-workbench">
    <header className="page-heading"><div><h1>素材智能分析</h1><p>Agent 先理解全部视频，再给出可审核的广告时间线。</p></div><span className="status-badge status-warning">{demo ? "演示分析" : "已完成分析"}</span></header>
    <div className="workbench-understanding"><section className="surface"><div className="surface-heading"><h2><Sparkles size={17} />AI 理解的剪辑要求</h2><span className="source-badge info">自然语言</span></div><div className="prompt-panel">把两个素材重新剪成 45 秒的印尼 TikTok 广告，节奏快一点，突出产品多功能，去掉中文声音，改成印尼语字幕和配音。</div><div className="tag-row"><span>45 秒</span><span>9:16</span><span>移除原声</span><span>印尼语字幕</span><span>女性配音</span></div></section><section className="surface"><h2>全片理解摘要</h2><div className="analysis-stats"><div><strong>18 / 31</strong><span>有效镜头</span></div><div><strong>7 段</strong><span>产品清晰露出</span></div><div><strong>4 段</strong><span>完整使用动作</span></div><div><strong>2 组</strong><span>前后对比</span></div></div></section></div>
      <div className="analysis-workspace"><section className="surface asset-map"><div className="surface-heading"><h2>素材价值地图</h2><span className="source-badge success">后台完整分析</span></div><div className="asset-tabs"><button className="active">推荐 18</button><button>重复 6</button><button>低质 4</button><button>风险 3</button></div>{clips.map(([title, description, score]) => <article className="analysis-clip" key={title}><div className="clip-visual"><Film size={18} /></div><div><strong>{title}</strong><p>{description}</p><span>{score}</span></div></article>)}</section><section className="surface timeline-editor"><div className="surface-heading"><h2>45 秒剪辑时间线</h2><button className="button">查看逐秒分析</button></div><div className="timeline-ruler"><span>0s</span><span>5</span><span>10</span><span>15</span><span>20</span><span>25</span><span>30</span><span>35</span><span>40</span><span>45s</span></div><div className="timeline-track"><b>画面</b><div className="timeline-blocks"><span className="block green">问题开场<br />A 03–07</span><span className="block amber">产品+喷洒<br />B 06–18</span><span className="block blue">擦拭过程<br />A 24–33</span><span className="block purple">前后对比<br />B 28–38</span><span className="block green">产品收尾<br />A 45–51</span></div></div><div className="timeline-track"><b>配音</b><div className="waveform">印尼语女性配音 · 按镜头节奏分句</div></div><div className="timeline-track"><b>字幕</b><div className="caption-track">Noda minyak membandel? Semprot, tunggu, lalu lap hingga bersih.</div></div><section className="agent-reasons"><h3>Agent 为什么这样组织</h3><p><b>0–4 秒</b> 先展示最明显油污，建立问题钩子。</p><p><b>4–15 秒</b> 产品先出现，再进入喷洒动作，保证识别。</p><p><b>25–38 秒</b> 清洁前后连续放置，形成明确对比。</p><p><b>38–45 秒</b> 包装和容量收尾，不虚构额外功效。</p></section></section><aside className="surface preview-workbench"><div className="surface-heading"><h2>低成本预览片</h2><Play size={17} /></div><div className="preview-frame"><div className="preview-product"><span>500 ml</span></div><strong>Lebih mudah membersihkan<br />noda minyak di dapur</strong></div><div className="preview-time"><span>00:17</span><i /><span>00:45</span></div><label className="revision-field"><span>用自然语言修改</span><textarea value={revision} placeholder="例如：开场换成油污更明显的画面，擦拭过程缩短 2 秒。" onChange={(event) => setRevision(event.target.value)} /></label><div className="button-row"><button className="button primary" onClick={() => onRevise?.(revision)}>让 Agent 修改方案<ArrowRight size={15} /></button><button className="button">确认并生成高清成片</button></div></aside></div>
  </section>;
}
